services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: web_prod
    command: gunicorn tablenow.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./app:/usr/src/app/
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1313:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
  db:
    image: postgres:15
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"

volumes:
  pgdata:
  static_volume: