services:
  web_dev:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: web_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/static
      - ./app:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

volumes:
  static:
  pgdata: